### ISSUE TITLE
Several questions

### ISSUE THREAD

**Issue by AKB-OU** [danielguterding/dhva#1]
Dear danielguterding,

Thank you for your very nice code "dhva" to be open to the public!

I have several queries about this code.

Regarding the angle phi, README file says that "phi=90"  will lead to a situation where the magnetic field is "parallel" to the kz-axis,
but is this correct?
Judging from the output, "phi=0" seems to correspond to the "parallel" case.

In addition, the code sometimes returns "Segmentation fault (core dumped)" after the message "Started matching fermi surface sheets".
With my input bxsf, the above error appears when I set phi=90, but it correctly works when I set phi=0.
Is this a possible bug, or an environment-dependent issue?

For your reference, I attached my input bxsf.
[band_rev.bxsf.zip](https://github.com/danielguterding/dhva/files/7073801/band_rev.bxsf.zip)
(In this input, the reciprocal lattice vector is given by 2*pi/a etc. in unit of angstrom^-1, so I think I should modify files.cpp to obtain correct crosssection and cyclotron mass)
The calculation condition is as follows: ./dhva band_rev.bxsf.band-8 1 400 6 0or90 0 0.05 0.01 10 1 0

Best regards,
AKB-OU

**Comment by danielguterding** [comment]
Sorry for coming back to you so late and thank you for reporting a bug. The crash you observed was a simple software bug, which is now solved on the master branch. Also, you observation regarding the angle phi is correct. I corrected the README. Please let me know whether this solves your questions.

**Comment by AKB-OU** [comment]
Thank you for your reply.
Using the debugged version, the calculation was successfully finished without segmentation fault.
My concerns are now all cleared up.
Many thanks.

**Comment by danielguterding** [comment]
Thank you for reporting. I am closing this issue.
